# Generated by Django 3.2.8 on 2021-10-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_address', models.CharField(max_length=500)),
                ('sponsor_phone', models.IntegerField()),
                ('sponsor_email', models.EmailField(max_length=254)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('next_of_kin_phone', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=11)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=10)),
                ('lga', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=11)),
                ('date_of_birth', models.DateTimeField()),
                ('biography', models.CharField(max_length=500)),
                ('date_of_registration', models.DateTimeField()),
            ],
        ),
    ]
